### ISSUE TITLE
Interactive test pagina werkt niet altijd ok 

### ISSUE THREAD

**Issue by RobbertK** [MapOnline/interactive#11]
patrickvanhoeijen commented 25 days ago • edited
Op PC John werkt het wel in Firefox, in Chrome werkt hovering niet juist, zie filmpje.
Om mijn laptop werkt het in chrome wel goed.

Wat is hier mis?

Dit is de inline code:

`<div id='m4n-9l8tzc3rtohcxia1nhfr'><script src='https://online.maps4news.com/ia/2.0/m4n.js'></script><script>var map = new M4nInteractive({"path": 'DC8/502/C0923A1A5D42AC379390F72FDD', "environment": 'online'}, document.getElementById( 'm4n-9l8tzc3rtohcxia1nhfr' )); </script></div>`

een swf filmpje hoe het op PC John gaat staat hier op dropbox:
...\MapCreator Shared\Development\Interactive

**Comment by beschoenen** [comment]
@patrickvanhoeijen Kan ik het filmpje krijgen, Ik ben geen lid van Dropbox.

**Comment by patrickvanhoeijen** [comment]
ik krijg de zip hier niet bijgevoegd, stuur het je per email.

**Comment by beschoenen** [comment]
#7
