### ISSUE TITLE
Move of map when showing popup at sides not enough (Bild)

### ISSUE THREAD

**Issue by Microbie** [MapOnline/interactive#12]
When you click on an icon on the sides of the map, the map moves 5 pixels. 
1) this number should be a constant at the top of the js file. See m4n.js lines #1244-#1257
2) 5 is not enough as the current popup has a larger gap between the tip and the side
3) the code does not work when the icon is at the bottom of the screen (bottom has a different value here)

**Comment by beschoenen** [comment]
#14
