### ISSUE TITLE
Bild: twee issues mbt interactive maps: witte lijnen en font stijl probleem.

### ISSUE THREAD

**Issue by patrickvanhoeijen** [MapOnline/interactive#13]
Bild meldt hier twee dingen: blijkbaar witte lijnen in zijn interactieve kaart (ik heb getest maar nergens witte lijnen bij deze URL), en fonts die niet correct weergeven qua stijl (bold).

Kunnen jullie dit checken?

Screen dumps:

font stijl wordt niet meegenomen:
https://online.maps4news.com/ia/2.0/iframe/?path=D62/CE3/70E7104D0D6D9AD9AD1159D693&env=online&id=m4n-0mtye9

![image](https://cloud.githubusercontent.com/assets/8438846/16301777/91b99660-3947-11e6-8d99-f5e509e774ca.png)

witte lijnen in kaartbeeld:
https://online.maps4news.com/ia/2.0/iframe/?path=F86/F20/96108BC2D912C86288B5EB406A&env=online&id=m4n-af4s96
![image](https://cloud.githubusercontent.com/assets/8438846/16301800/b3ac77a6-3947-11e6-9d9d-11d8fc503c1a.png)

**Comment by patrickvanhoeijen** [comment]
@beschoenen blijkbaar gebeurt dit op safari en firefox (ook op windows, zie image) (op chrome gaat t goed):

![image](https://cloud.githubusercontent.com/assets/8438846/16304468/e2aa0aec-3955-11e6-9c99-a5ca1ea0a9d8.png)

**Comment by beschoenen** [comment]
@doskabouter Can you look at the style error?

**Comment by beschoenen** [comment]
@patrickvanhoeijen I made 2 maps with and without bold and it looks fine to me.

![60446](https://cloud.githubusercontent.com/assets/1887585/17102075/23c4a90c-5278-11e6-8f3a-f9715e64d177.png)
![60445](https://cloud.githubusercontent.com/assets/1887585/17102076/23c64cbc-5278-11e6-9ac0-139e15402551.png)

And that the lines don't show on Chrome means that it's an issue in the browsers themselves.
