### ISSUE TITLE
Inline map object

### ISSUE THREAD

**Issue by beschoenen** [MapOnline/interactive#21]
Proposal:
Add the map object inline into the constructor

``` js
var map = new M4nInteractive({
    path: "path/to/map",
    environment: "online",
    interact: "controls",
    object: { // map.json object
        levels: ... 
    }
}, document.getElementById("m4n-map"));
```

**Comment by beschoenen** [comment]
97fcf0c

**Comment by dazlious** [comment]
Does closed mean "finished" or does closed mean, won't be done?
When is your next release of 2.0.5-1? We would appreciate this feature ;)

**Comment by beschoenen** [comment]
I just added the code in the 2.0.5-1 release, which will hopefully be released later this week.

**Comment by dazlious** [comment]
works just fine. Many thanks!
