### ISSUE TITLE
Overlay, Sidebar en Hover werken niet

### ISSUE THREAD

**Issue by patrickvanhoeijen** [MapOnline/interactive#29]
### What happened?

Overlay, Sidebar and Hover all do not work well, for inline as well as iframe: all become Popover and Click output:
![image](https://cloud.githubusercontent.com/assets/8438846/17764445/a2e5ece6-651f-11e6-824b-caff626016d7.png)
### What did you expect to happen?

these options should work well like before
### Steps to reproduce
1. create a map with an interactive icon on it and use one of these 3 options when generating your map: test the inline or iframe output code on our demo page..

**Comment by beschoenen** [comment]
@patrickvanhoeijen Please reopen your issue in **English** and read the [contributing guidelines](https://github.com/MapOnline/interactive/blob/master/.github/CONTRIBUTING.md).

**Comment by patrickvanhoeijen** [comment]
@beschoenen I do not have rights to re-open this issue.

**Comment by RobbertK** [comment]
MapOnline issue.
