### ISSUE TITLE
size in iframe output is not the chosen size by user

### ISSUE THREAD

**Issue by patrickvanhoeijen** [MapOnline/interactive#30]
### What happened?

User created this output (online 64244):
`<iframe width="75" height="50" allowfullscreen="allowfullscreen" src="https://online.maps4news.com/ia/2.0/iframe/?path=EC0/247/A6A52AE10F3795DADE7E1B8D0B&env=online"></iframe>`

75x50 pixels, but the size in the job is 75x50 mm, so should be calculated to pixels units: 475x283
### What did you expect to happen?

if user selects size in mm (or inches) for web output, the values should be calculated to px (seems to happen when testing this, so what caused this failure is the question??)
### Steps to reproduce
1. copy code above, paste it in demo page iframe field
2. clone job, see dimensions are 75x50mm

**Comment by beschoenen** [comment]
This is an issue for the tool.
